---
name: Objetos y mensajes
locale: es
type: learning
beta: false
teacher_info: ''
language: wollok
id_format: '%05d'
order:
- 1
- 18
- 19
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
