---
name: Objetos y mensajes
locale: es
type: learning
beta: false
teacher_info: ''
language: wollok
id_format: '%05d'
order:
- 1
- 22
- 19
- 23
- 24
- 25
- 26
- 31
- 32
- 29
- 30
- 27
- 28
- 33
- 34
